server:
   port: 8085

jwt:
 secret: ${JWT_SECRET:8tk6svJ8XE26nxQOAMW8XBWsgJMHuAjHxCBCh9aw3ds=}
 
spring:
   cloud:
      gateway:
         routes:
         -  id: bms-authuser-service
            uri: lb://BMS-AUTHUSER-SERVICE
            predicates:
            - Path=/bms/auth/**
            filters:
            - JwtAuthenticationFilter


eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
